- name: Cloning repository
  git:
    repo: "https://github.com/jubeenshah/checkbox.io.git"
    dest: "{{home_path}}/checkbox.io"
    force: true

- name: Create mongodb Database and User
  mongodb_user:
    database: admin
    name: "{{env_vars.MONGO_USER}}"
    password: "{{env_vars.MONGO_PASSWORD}}"
    state: present
    roles: readWrite,dbAdmin,userAdmin

- name: NPM Install (shell command)
  become: true
  shell: npm install
  args:  
    chdir: "{{home_path}}/checkbox.io/server-side/site/"
    creates: .modules-installed.txt

- name: Installing pm2
  npm:
    name: pm2
    global: yes
    state: present

- name: "Check list of Node.js apps running."
  become: no
  command: pm2 list
  register: pm2
  changed_when: false

- name: Installing express
  become: true
  apt:
    name: ['node-express-generator']
    state: present

#- name: Linking dependencies
 # become: true
 # shell: npm link cors
 # args:
 #   creates: .link-cors.txt 

- name: Installing dependencies
  become: true
  npm:
    name: cors
    global: yes
    state: present

#- name: NPM Install (shell command)
#  become: true
#  shell: npm install -g
#  args:
#    chdir: "{{home_path}}/checkbox.io/server-side/site/"
#    creates: .modules-installed.txt

#- name: "Start checkbox api server app."
#  become: true
#  shell: pm2 start server.js -f
#  args:
#   chdir: "{{home_path}}/checkbox.io/server-side/site/"
#  environment: "{{env_vars}}"
#  when: "pm2.stdout.find('server') == -1"

- name: update config file
  blockinfile:
    dest: "{{nginx_config_path}}"
    insertbefore: "sendfile on;"
    block: "upstream app_nodejs_design {
      server 127.0.0.1:3002;
      }"

- name: Replacing the site-enable config
  template:
    force: yes
    src: "templates/default.conf.j2"
    dest: "{{nginx_sites_path}}"
    mode: 0700

- service: 
    name: nginx
    state: restarted


- name: Copying package.json
  become: true
  copy:
    src: package.json
    dest: "{{home_path}}/checkbox.io/server-side/site/package.json"

- name: creating test/
  file:
    path: "{{home_path}}/checkbox.io/server-side/site/test/"
    state: directory

- name: Copying test.js
  become: true
  copy:
    src: test.js
    dest: "{{home_path}}/checkbox.io/server-side/site/test/test.js"

- name: Copying package.json
  become: true
  copy:
    src: startstop.js
    dest: "{{home_path}}/checkbox.io/server-side/site/startstop.js"

- name: NPM Install (shell command)
  become: true
  shell: npm install
  args:  
    chdir: "{{home_path}}/checkbox.io/server-side/site/"
    creates: .modules-installed.txt

- name: Installing pm2
  npm:
    name: pm2
    global: yes
    state: present

- name: "Check list of Node.js apps running."
  become: no
  command: pm2 list
  register: pm2
  changed_when: false

- name: Installing express
  become: true
  apt:
    name: ['node-express-generator']
    state: present

#- name: Linking dependencies
 # become: true
 # shell: npm link cors
 # args:
 #   creates: .link-cors.txt 

- name: Installing dependencies
  become: true
  npm:
    name: cors
    global: yes
    state: present

#- name: NPM Install (shell command)
#  become: true
#  shell: npm install -g
#  args:
#    chdir: "{{home_path}}/checkbox.io/server-side/site/"
#    creates: .modules-installed.txt

#- name: "Start checkbox api server app."
#  become: true
#  shell: pm2 list
#  args:
#   chdir: "{{home_path}}/checkbox.io/server-side/site/"
#  environment: "{{env_vars}}"
#  when: "pm2.stdout.find('server') == -1"

- name: Copying JJB file to target machine
  copy:
    src: checkbox-build.yml
    dest: /home/vagrant/jenkins-job-builder/checkbox-build.yml

- name: Configuring the build job
  shell: jenkins-jobs --conf /etc/jenkins_job/jenkins_jobs.ini --user admin --password admin update checkbox-build.yml
  args:
    chdir: /home/vagrant/jenkins-job-builder

#- name: Running the Build job for itrust
#  command: curl -X POST http://admin:admin@127.0.0.1:9999/job/checkbox/build


- service: 
    name: nginx
    state: restarted
