---
- name: Configuring Jenkins
  hosts: all
  become: true
  gather_facts: false
  roles: 
    - jenkins
    - install-modules
    - nginx
    - node
    - mongodb
    - JJB
    - mysql
    - maven
    - chrome
    - checkbox
    - itrust
    - build
    #- githooks
    #- fuzzer
    #- checkbox-analysis
    #- itrust-analysis
