---
- name: Configuring Jenkins
  hosts: all
  become: true
  gather_facts: true
# Would prefer to add a role for checkbox and combine nginx, node and mongoDB roles.
  roles: 
    - jenkins
    - install-modules
    - nginx
    - node
    - mongodb
    - JJB
    - mysql
    - maven
    - chrome
    - checkbox
    - itrust
    #- build
    - githooks
