# Handler to start the MySQL service
- name: Start MySQL
  become: true
  service:
    name: mysql
    state: started
    enabled: true

- name: Restart MySQL
  become: true
  service:
    name: mysql
    state: restarted
    enabled: true
    
# not currently being used, but for future use
- name: Stop MySQL
  become: true
  service:
    name: mysql
    state: stopped
