#MongoDB
home_path: /home/ubuntu
nginx_sites_path: /etc/nginx/sites-enabled/default
nginx_config_path: /etc/nginx/nginx.conf
env_vars: 
    MONGO_PORT: "3002"
    MONGO_IP: "localhost"
    MONGO_USER: "admin"
    MONGO_PASSWORD: "admin"
    MAIL_SMTP: "smtp.gmail.com"
