- name: Start Jenkins
  become: true
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Restart Jenkins
  become: true
  systemd:
    name: jenkins
    state: restarted
 
 - name: Update apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages