- name: Including variables.yml
  include_vars:
    file: variables.yml

- name: Getting iTrust Repository
  git: 
    repo: "{{itrust_repo}}"
    dest: "{{home_path}}/iTrust"
    force: yes

- name: Changing Permissions 
  file:
    path: "{{home_path}}/iTrust/iTrust2"
    mode: 0777

- name: Copy a "db.properties.template" file on the remote machine for editing
  copy:
    src: "{{home_path}}/{{db_path}}/db.properties.template"
    dest: "{{home_path}}/{{db_path}}/db.properties"
    remote_src: yes

- name: Deleting Old file of db
  file:
    path: "{{home_path}}/{{db_path}}/db.properties.template"
    state: absent

- name: Copy a "email.properties.template" file on the remote machine for editing
  copy:
    src: "{{home_path}}/{{db_path}}/email.properties.template"
    dest: "{{home_path}}/{{db_path}}/email.properties"
    remote_src: yes

- name: Deleting Old file of email
  file: 
    path: "{{home_path}}/{{db_path}}/email.properties.template"
    state: absent

- name: Copying the new email.properties with updated credentials
  template:
    src: email.properties.j2
    dest: "{{home_path}}/{{db_path}}/email.properties"

- name: Copying JJB file to target machine (Without static analysis)
  copy:
    src: itrust-build.yml
    dest: "{{home_path}}/iTrust/iTrust2/"

- name: Configuring the build job
  shell: jenkins-jobs --conf /etc/jenkins_job/jenkins_jobs.ini --user admin --password admin update itrust-build.yml
  args:
    chdir: "{{home_path}}/iTrust/iTrust2/"
    
- name: Setting timezone for itrust build
  timezone:
    name: America/New_York
