- job:
    name: Checkbox-analysis
    builders:
    - shell: "cd /home/vagrant/checkbox.io/server-side/site/checkbox-analysis; npm test; npm run test-jenkins"
    wrappers:
    - ansicolor:
        colormap: "xterm"
