---
# tasks file for ansible
- name: Including Variables.yml
  include_vars:
    file: variables.yml

- name: Installing software-properties-common
  become: true
  apt:
    name: ['software-properties-common']

- name: Adding repository for Ansible
  become: true
  apt_repository:
    repo: 'ppa:ansible/ansible'
  tags:
    - Update apt packages

- name: Installing ansible
  become: true
  apt:
    name: ['ansible']

- name: host_key_checking is set to false
  become: true
  copy:
     src: ansible.cfg
     dest: /etc/ansible/ansible.cfg

- name: Configuring the build job for iTrust
  shell: "jenkins-jobs --conf /etc/jenkins_job/jenkins_jobs.ini --user {{jenkins_user}} --password {{jenkins_password}} update configure-ansible.yml"
  args:
    chdir: "{{home_path}}"

- name: Copying JJB file for checkbox
  copy:
    src: configure-checkbox.yml
    dest: "{{home_path}}"

- name: Configuring the build job for checkbox and kubernetes
  shell: "jenkins-jobs --conf /etc/jenkins_job/jenkins_jobs.ini --user {{jenkins_user}} --password {{jenkins_password}} update configure-checkbox.yml"
  args:
    chdir: "{{home_path}}"

- name: Setting up another AWS instance
  become: true
  shell: |
          chmod 777 -R /home/ubuntu/; ansible-playbook setUpLocal-2.yml; sleep 30; chmod 600 DevOps-pro-2.pem

- name: Setting permissions for root
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Setting permissions for jenkins
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'jenkins ALL= NOPASSWD: ALL'
    validate: 'visudo -cf %s'

#- name: Running the Build job for iTrust
#  command: "curl -X POST http://{{jenkins_user}}:{{jenkins_password}}@127.0.0.1:{{jenkins_port}}/job/Configure/build"
 


