#should be part of a 'tasks'
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Adding repository for Java
  become: true
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  tags:
    - Update apt packages

- name: Adding the apt signing key for Jenkins
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present
  tags:
    - Update apt packages

- name: Creating a jenkins.list file in /etc/apt/sources.list.d/
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: 'deb http://pkg.jenkins.io/debian-stable binary/'
    create: yes
  tags:
    - Update apt packages

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Installing openjdk-8-jdk, openjdk-8-jre
  become: true
  apt:
    update_cache: yes
    state: latest
    force: yes
    name: ['openjdk-8-jdk','openjdk-8-jre']
  tags:
    - Installing dependencies
  
- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Installing Jenkins
  become: true
  apt:
    update_cache: yes
    state: latest
    force: yes
    name: ['jenkins']
  notify: Start Jenkins
  tags:
    - Installing dependencies

# Move to handlers later on
#- name: Start & Enable Jenkins
#  systemd:
#    name: jenkins
#    state: started
#    enabled: true

# Check if you really need this file
- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Copying jenkins.install.UpgradeWizard.state to target machine
  copy:
    src: jenkins.install.UpgradeWizard.state
    dest: /var/lib/jenkins/jenkins.install.UpgradeWizard.state
  notify: Restart Jenkins
  tags: 
    - Jenkins Configuration

- name: "Turn off Jenkins setup wizard"
  lineinfile:
      dest: /etc/init.d/jenkins
      regexp: '^JAVA_ARGS='
      line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      insertbefore: '^DAEMON_ARGS='
  notify: Restart Jenkins
  tags: 
    - Jenkins Configuration

# No longer need it
#- name: Copying the initial Admin password
#  become: true
#  command: cat /var/lib/jenkins/secrets/initialAdminPassword
#  register: output

#- debug:
#    msg: output.stdout

- name: Creating init.groovy.d
  become: true
  file: 
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: root
    group: root
    mode: 0775
  tags: 
    - Jenkins Configuration

- name: Copying Groovy file to target machine
  template:
    src:  setup-admin.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/setup-admin.groovy
  notify: Restart Jenkins
  tags: 
    - Jenkins Configuration

- name: Copying the default configuration on target machine
  template:
    src: jenkins.j2
    dest: /etc/default/jenkins
  tags:
    - Jenkins Configuration

- name: Restart Jenkins
  become: true
  systemd:
    name: jenkins
    state: restarted
# Next step is user creation and setup
