---
# tasks file for AWS Configuring AWS

- name: Including variables.yml
  include_vars:
    file: variables.yml

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages
  
#- name: Installing npm and nodejs
#  become: true
#  apt:
#    name:  ['npm', 'nodejs-legacy']
    
- name: Copying AWS content
  become: true
  shell: cp -r /ansible-srv/AWS/ ~/AWS/; sudo chmod -R 777 ~/AWS/

- name: Npm install AWS
  shell: npm install
  args:
    chdir: ~/AWS/

- name: Installing awscli
  become: true
  apt:
    name: awscli

- name: Configuring AWS
  shell: |
      aws configure set aws_access_key_id "{{access_key_id}}"
      aws configure set aws_secret_access_key "{{secret_access_key}}"
      aws configure set default.region "{{aws_az}}"
    
  
#- name: Executing AWS
#  become: false
#  shell: node aws.js
#  args:
#    chdir: ~/AWS/

#- name: Sleep for 10 seconds
#  wait_for:
#    timeout: 10
    
