- job:
    name: Configure-Checkbox
    builders:
    - shell: |
           cd /home/ubuntu/
           sudo ansible-playbook -i inventory roles/kubernetes/tasks/main.yml -vv
    triggers:
    - github
    #I need to add some post build tasks for setting up the itrust repo on the remote machine?? Do i still need to? still need to have the kubernetes playbook.yml run
    # shift the setUpLocal2.yml ansible here

    

