- name: Getting iTrust Repository
  git: 
    repo: https://github.com/rayandasoriya/iTrust.git
    dest: /home/vagrant/iTrust
    force: yes

- name: Changing Permissions 
  file:
    path: "/home/vagrant/iTrust/iTrust2"
    mode: 0777

- name: Copy a "db.properties.template" file on the remote machine for editing
  copy:
    src: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties.template
    dest: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties
    remote_src: yes

- name: Deleting Old file of db
  file:
    path: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties.template
    state: absent

#- name: Deleting Old file of email
#  file:
#    path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
#    state: absent

- name: Copy a "email.properties.template" file on the remote machine for editing
  copy:
    src: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
    dest: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties
    remote_src: yes

- name: Deleting Old file of email
  file: 
    path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
    state: absent

- name: Copying the new email.properties with updated credentials
  template:
    src: email.properties.j2
    dest: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties

- name: Copying JJB file to target machine
  copy:
    src: itrust-build.yml
    dest: /home/vagrant/jenkins-job-builder/itrust-build.yml

- name: Configuring the build job
  shell: jenkins-jobs --conf /etc/jenkins_job/jenkins_jobs.ini --user admin --password admin update itrust-build.yml
  args:
    chdir: /home/vagrant/jenkins-job-builder

- name: Running the Build job for itrust
  command: curl -X POST http://admin:admin@127.0.0.1:9999/job/iTrust2/build
