- name: Getting iTrust Repository
  git: 
    repo: https://github.com/rayandasoriya/iTrust.git
    dest: /home/vagrant/iTrust
    force: yes

- name: Changing Permissions 
  file:
    path: "/home/vagrant/iTrust/iTrust2"
    mode: 0777

- name: Copy a "db.properties.template" file on the remote machine for editing
  copy:
    src: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties.template
    dest: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties
    remote_src: yes

- name: Deleting Old file of db
  file:
    path: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties.template
    state: absent

#- name: Deleting Old file of email
#  file:
#    path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
#    state: absent

- name: Copy a "email.properties.template" file on the remote machine for editing
  copy:
    src: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
    dest: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties
    remote_src: yes

- name: Deleting Old file of email
  file: 
    path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
    state: absent
